### ISSUE TITLE
Local LLM Issue - send_to field is None

### ISSUE THREAD

**Issue by dhifafaz** [microsoft/TaskWeaver#113]
I try to use local LLM using several local model, such as deepseek-6.7b, mistral-7b, dolphine-2.1-mistral-7b.
When i give taskweaver ordinary message such hai, on model dolphine it going fine but when i try triggering with question that need function calling it return some error. But when i'm using deepseek and mistral, im just sending hello, and it return the same error that i found on dolphine model.

I'm using text-gen-webui/oobabooga, the latest pull from their repo to serve the model. I also activate the open ai extension. 

This is the error

```
TaskWeaver: I am TaskWeaver, an AI assistant. To get started, could you please enter your request?
Human: can you please make this word 'ABC' into ascii art
Error: Cannot process your request due to Exception: Planner failed to generate response because send_to field is None 
 Traceback (most recent call last):
  File "mypath/TaskWeaver/taskweaver/planner/planner.py", line 222, in reply
    response_post = self.planner_post_translator.raw_text_to_post(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mypath/TaskWeaver/taskweaver/role/translator.py", line 86, in raw_text_to_post
    validation_func(post)
  File "mypath/TaskWeaver/taskweaver/planner/planner.py", line 207, in check_post_validity
    assert post.send_to is not None, "send_to field is None"
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: send_to field is None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mypath/TaskWeaver/taskweaver/session/session.py", line 135, in send_message
    post = _send_message(post.send_to, post)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mypath/TaskWeaver/taskweaver/session/session.py", line 107, in _send_message
    reply_post = self.planner.reply(
                 ^^^^^^^^^^^^^^^^^^^
  File "mypath/TaskWeaver/taskweaver/planner/planner.py", line 244, in reply
    raise Exception(f"Planner failed to generate response because {str(e)}")
Exception: Planner failed to generate response because send_to field is None

Human: 
```
I'm using transformers and llama.cpp loader for this one
Any clue ? anyone? thanks

**Comment by liqul** [comment]
This is because the LLM failed to generate response according to our protocol, missing the `send_to` field.

**Comment by dhifafaz** [comment]
ooo basically it's not following the system prompt right?

**Comment by liqul** [comment]
Yes, we have a retry mechanism, but if it fails for 3 times, we will raise this exception.

**Comment by dhifafaz** [comment]
aaaa i see, thank you very much for your help
