### ISSUE TITLE
RuntimeError: cannot reuse already awaited coroutine

### ISSUE THREAD

**Issue by super-buster** [microsoft/TaskWeaver#143]
**Describe the bug**
Run Task "generate 10 numbers" fails.

**To Reproduce**
2024-01-19 01:27:33 - Your app is available at http://localhost:8000
2024-01-19 01:27:42 - Planner initialized successfully
2024-01-19 01:27:42 - CodeInterpreter initialized successfully.
2024-01-19 01:27:42 - Session 20240118-172742-f3d895df is initialized
2024-01-19 01:27:49 - Use back up engine: False
2024-01-19 01:27:53 - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2024-01-19 01:27:59 - LLM output: {"response": [{"type": "init_plan", "content": "1. Generate 10 random numbers"}, {"type": "plan", "content": "1. Generate 10 random numbers"}, {"type": "current_plan_step", "content": "1. Generate 10 random numbers"}, {"type": "send_to", "content": "CodeInterpreter"}, {"type": "message", "content": "Please generate 10 random numbers"}]}

**Screenshots**
![屏幕截图 2024-01-19 013156](https://github.com/microsoft/TaskWeaver/assets/38288897/c3923c0d-3921-4908-95bf-e8d71248e4b3)

**Additional context**
LLM: gpt-3.5-turbo-1106

**Comment by ashikns** [comment]
Try upgrading langchain and openai to latest.

**Comment by liqul** [comment]
Close inactive issues.

**Comment by Basilio6** [comment]
Hi,

I have the same problem. I tried to ugrade openai to latest (langchain is not installed) but it did not solved it.
Do you have any idea ?

    Human   ▶  generate 10 numbers
 ╭───< Planner >
 ├─► [init_plan] 1. generate 10 random numbers
 ├─► [plan] 1. instruct CodeInterpreter to generate 10 random numbers
 ├─► [current_plan_step] 1. instruct CodeInterpreter to generate 10 random numbers
 ├──● Please generate 10 random numbers
 ╰──● sending message to CodeInterpreter
 ╭───< CodeInterpreter >
 ├─► [thought] ProgramApe will generate a code snippet using the numpy library to create an array of 10 random numbers.
 ├─► [python]
 │   import numpy as np
 │   random_numbers = np.random.rand(10)
 │   print(random_numbers)
 ├─► [verification] NONE
 ├─► [code_error] No code verification is performed.
 ╰──● sending message to Planner
Error: Cannot process your request due to Exception: This event loop is already running 
 Traceback (most recent call last):
  File "/volume1/web/TaskWeaver/taskweaver/session/session.py", line 141, in _send_text_message
    post = _send_message(post.send_to, post)
  File "/volume1/web/TaskWeaver/taskweaver/session/session.py", line 124, in _send_message
    reply_post = self.code_interpreter.reply(
  File "/volume1/web/TaskWeaver/taskweaver/code_interpreter/code_interpreter.py", line 202, in reply
    exec_result = self.executor.execute_code(
  File "/volume1/web/TaskWeaver/taskweaver/code_interpreter/code_executor.py", line 67, in execute_code
    self.start()
  File "/volume1/web/TaskWeaver/taskweaver/code_interpreter/code_executor.py", line 128, in start
    self.exec_client.start()
  File "/volume1/web/TaskWeaver/taskweaver/ces/manager/sub_proc.py", line 27, in start
    self.mgr.env.start_session(self.session_id, session_dir=self.session_dir, cwd=self.cwd)
  File "/volume1/web/TaskWeaver/taskweaver/ces/environment.py", line 176, in start_session
    session.kernel_id = self.multi_kernel_manager.start_kernel(
  File "/volume1/web/TaskWeaver/TaskWeaver_env/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/var/packages/python310/target/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/volume1/web/TaskWeaver/TaskWeaver_env/lib/python3.10/site-packages/jupyter_client/multikernelmanager.py", line 271, in _async_start_kernel
    starter = ensure_async(km.start_kernel(**kwargs))
  File "/volume1/web/TaskWeaver/TaskWeaver_env/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/var/packages/python310/target/lib/python3.10/asyncio/base_events.py", line 625, in run_until_complete
    self._check_running()
  File "/var/packages/python310/target/lib/python3.10/asyncio/base_events.py", line 584, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

**Comment by liqul** [comment]
@Basilio6 Hi, this looks like an error raised when starting the Jupyter kernel. I found this old issue at Jupyter core https://github.com/jupyter/notebook/issues/5663. Could you check if the fix in that issue can help in your case?

**Comment by Basilio6** [comment]
Do someone has an idea ?
