### ISSUE TITLE
I get an error when I try to run the UI

### ISSUE THREAD

**Issue by yf007** [microsoft/TaskWeaver#148]
**Environment Information (please complete the following information):**
 - OS: [Windows]
 - Python Version [3.11]
 - LLM that you're using: [GPT-4]
 - Other Configurations except the LLM api/key related: [e.g., code_verification: true]

**Additional context**

When I try to run the UI I get this error:

PS E:\01.01.2024\Ai\TaskWeaver\TaskWeaver\playground\UI> chainlit run app.py
If UI is not started, please go to the folder playground/UI and run `chainlit run app.py` to start the UI
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\josef\AppData\Local\Programs\Python\Python311\Scripts\chainlit.exe\__main__.py", line 7, in <module>
  File "C:\Users\josef\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\josef\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\josef\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\josef\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\josef\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\josef\AppData\Local\Programs\Python\Python311\Lib\site-packages\chainlit\cli\__init__.py", line 154, in chainlit_run
    run_chainlit(target)
  File "C:\Users\josef\AppData\Local\Programs\Python\Python311\Lib\site-packages\chainlit\cli\__init__.py", line 55, in run_chainlit
    load_module(config.run.module_name)
  File "C:\Users\josef\AppData\Local\Programs\Python\Python311\Lib\site-packages\chainlit\config.py", line 282, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\01.01.2024\Ai\TaskWeaver\TaskWeaver\playground\UI\app.py", line 118, in <module>
    class ChainLitMessageUpdater(SessionEventHandlerBase):
  File "E:\01.01.2024\Ai\TaskWeaver\TaskWeaver\playground\UI\app.py", line 119, in ChainLitMessageUpdater
    def __init__(self, root_step: cl.Step):
                                  ^^^^^^^
  File "C:\Users\josef\AppData\Local\Programs\Python\Python311\Lib\site-packages\chainlit\utils.py", line 64, in __getattr__
    module_path = registry[name]
                  ~~~~~~~~^^^^^^
KeyError: 'Step'
PS E:\01.01.2024\Ai\TaskWeaver\TaskWeaver\playground\UI>

**Comment by yf007** [comment]
I have now installed it on env

And when the UI comes up, I get this message:
"{"detail":"Not Found"}" when I enter the address:"http://127.0.0.1:8000/"

**Comment by zhangxu0307** [comment]
You can try to upgrade the chainlit to the latest version.

**Comment by liqul** [comment]
close inactive issues
