### ISSUE TITLE
Cannot process your request due to Exception: Planner failed to generate response because LLM failed to generate complete attachments 

### ISSUE THREAD

**Issue by zuoxiang95** [microsoft/TaskWeaver#227]
**Describe the bug**
Cannot process your request due to Exception: Planner failed to generate response because LLM failed to generate complete attachments 

**To Reproduce**
1. Start the service
2. Type the user query "hi"
3. Wait for the response

**Screenshots**
```
Error: Cannot process your request due to Exception: Planner failed to generate response because LLM failed to generate complete attachments 
 Traceback (most recent call last):
  File "/home/zuoxiang/project/TaskWeaver/taskweaver/planner/planner.py", line 304, in reply
    self.planner_post_translator.raw_text_to_post(
  File "/home/zuoxiang/project/TaskWeaver/taskweaver/role/translator.py", line 133, in raw_text_to_post
    validation_func(post_proxy.post)
  File "/home/zuoxiang/project/TaskWeaver/taskweaver/planner/planner.py", line 261, in check_post_validity
    assert len(post.attachment_list) == 3, "LLM failed to generate complete attachments"
AssertionError: LLM failed to generate complete attachments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zuoxiang/project/TaskWeaver/taskweaver/session/session.py", line 153, in _send_text_message
    post = _send_message(post.send_to, post)
  File "/home/zuoxiang/project/TaskWeaver/taskweaver/session/session.py", line 127, in _send_message
    reply_post = self.planner.reply(
  File "/home/zuoxiang/project/TaskWeaver/taskweaver/planner/planner.py", line 327, in reply
    raise Exception(f"Planner failed to generate response because {str(e)}")
Exception: Planner failed to generate response because LLM failed to generate complete attachments
```

**Environment Information (please complete the following information):**
 - OS: Linux
 - Python Version 3.10
 - LLM that you're using: GPT-4]

**Comment by ShilinHe** [comment]
Hi, usually this issue is caused by a wrong LLM response that does not follow the expected json schema, you may check the raw LLM output in the project/logs/task_weaver.log. 
Also, did you remove any examples? sometimes this issue may happen if you remove the greeting example.
