### ISSUE TITLE
TaskWeaver failed to call llama2 of ollama

### ISSUE THREAD

**Issue by 13516513760** [microsoft/TaskWeaver#245]
I downloaded llama2 through Ollama and then changed the taskweaverConfig.json content of Taskweaver to
```
{
"Llm. api_base":“ http://localhost:11434 ",",
"Llm. api_key": null,
"Llm. api_type": "olama",
"Llm. model": "llama2:13b"
}
```
Unable to connect after starting Taskweaver, keeps reporting error:
```
Cannot process your request due to Exception: Failed to get completion with error code 503:
Traceback (most recent call last):
File "E: \ TaskWeaver \ TaskWeaver main \ playground \ UI../.. \ taskweaver \ session \ session. py", line 141, in _send_text_message
Post=_send_message (post. send_to, post)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E: \ TaskWeaver \ TaskWeaver main \ playground \ UI../.. \ taskWeaver \ session \ session. py", line 115, in send_message
Replypost=self. planner. reply（
^^^^^^^^^^^^^^^^^^^
File "E: \ TaskWeaver \ TaskWeaver main \ playground \ UI../.. \ taskweaver \ planner \ planner. py", line 304, in reply
Self. planner post_translator. raw_text_to post（
File "E: \ TaskWeaver \ TaskWeaver main \ playground \ UI../.. \ taskweaver \ role \ translator. py", line 74, in raw_text_to post
For type_str, value, is_end in parserstream:
File "E: \ TaskWeaver \ TaskWeaver main \ playground \ UI../.. \ taskweaver \ role \ translator. py", line 267, in parse_llm output_stream v2
For ev in parser:
File "E: \ TaskWeaver \ TaskWeaver main \ playground \ UI../.. \ taskweaver \ utils \ json_parser. py", line 389, in parse_json_stream
For chunk in itertools. chain (token_stream, [None]):
File "E: \ TaskWeaver \ TaskWeaver main \ playground \ UI../.. \ taskweaver \ role \ translator. py", line 54, in streamfilter
For c in s:
File "E: \ TaskWeaver \ TaskWeaver main \ playground \ UI../.. \ taskweaver \ planner \ planner. py", line 291, in streamfilter
For c in s:
File "E: \ TaskWeaver \ TaskWeaver main \ playground \ UI../.. \ taskweaver \ llm init. py", line 225, in stream_smoother
Raise llm_source_error # type: ignore
^^^^^^^^^^^^^^^^^^^^^^
File "E: \ TaskWeaver \ TaskWeaver main \ playground \ UI../.. \ taskweaver \ llm_it. py", line 173, in base_stream_puller
For msg in stream:
File "E: \ TaskWeaver \ TaskWeaver main \ playground \ UI../.. \ taskweaver \ llm \ ollama. py", line 119, in _chatcompletion
Raise exception（
Exception: Failed to get completion with error code 503:
```
May I ask what I should do

**Comment by Mioooooo** [comment]
Is the problem solved?
