### ISSUE TITLE
Error: Cannot process your request due to Exception: 'NoneType' object has no attribute 'content' 

### ISSUE THREAD

**Issue by g1ronn1mo** [microsoft/TaskWeaver#26]
```
Human: what time is it
>>> [INIT_PLAN]
1. Fetch the current system time
>>> [PLAN]
1. Fetch the current system time
>>> [CURRENT_PLAN_STEP]
Fetch the current system time
>>> [SEND_TO]
CodeInterpreter
>>> [MESSAGE]
Please provide the current system time.
>>> [PLANNER->CODEINTERPRETER]
Please provide the current system time.
Error: Cannot process your request due to Exception: 'NoneType' object has no attribute 'content' 
 Traceback (most recent call last):
  File "/home/bene/Pojects/TaskWeaver/taskweaver/session/session.py", line 125, in send_message
    post = _send_message(post.send_to, post)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bene/Pojects/TaskWeaver/taskweaver/session/session.py", line 107, in _send_message
    reply_post = self.code_interpreter.reply(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bene/Pojects/TaskWeaver/taskweaver/code_interpreter/code_interpreter.py", line 68, in reply
    code.content,
    ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'content'
```

**Environment Information (please complete the following information):**
 - OS: Ubuntu 23.10
 - Python 3.11.6
 - LLM that you're using: GPT-4-preview
 - code_verification: true

**Comment by tendaysaweek** [comment]
getting same issues using llama and mistral  & gpt4

Error: Cannot process your request due to Exception: 'NoneType' object has no attribute 'content'
 Traceback (most recent call last):

**Comment by g1ronn1mo** [comment]
I think that has to do with missing files. The program tries to load a functioncaller.yml, but this file is not there. Do you have these files created?

**Comment by tendaysaweek** [comment]
no such file in the folders, any suggestion how to solve:?
