### ISSUE TITLE
cant execute generated code  in Google colab

### ISSUE THREAD

**Issue by sangeet000007** [microsoft/TaskWeaver#271]
i have tested both gemini-pro and gemini-1.5-pro-latest model both failed to execute the generated code 
the error shown is
```
2024-03-28 09:07:34 - Traceback (most recent call last):
  File "/content/TaskWeaver/playground/UI/../../taskweaver/session/session.py", line 166, in _send_text_message
    post = _send_message(post.send_to, post)
  File "/content/TaskWeaver/playground/UI/../../taskweaver/module/tracing.py", line 174, in wrapper
    return func(*args, **kwargs)
  File "/content/TaskWeaver/playground/UI/../../taskweaver/session/session.py", line 150, in _send_message
    reply_post = self.worker_instances[recipient].reply(
  File "/content/TaskWeaver/playground/UI/../../taskweaver/module/tracing.py", line 186, in wrapper
    return func(self, *args, **kwargs)
  File "/content/TaskWeaver/playground/UI/../../taskweaver/code_interpreter/code_interpreter/code_interpreter.py", line 234, in reply
    exec_result = self.executor.execute_code(
  File "/content/TaskWeaver/playground/UI/../../taskweaver/module/tracing.py", line 186, in wrapper
    return func(self, *args, **kwargs)
  File "/content/TaskWeaver/playground/UI/../../taskweaver/code_interpreter/code_executor.py", line 71, in execute_code
    self.start()
  File "/content/TaskWeaver/playground/UI/../../taskweaver/code_interpreter/code_executor.py", line 139, in start
    self.exec_client.start()
  File "/content/TaskWeaver/playground/UI/../../taskweaver/ces/manager/sub_proc.py", line 27, in start
    self.mgr.env.start_session(self.session_id, session_dir=self.session_dir, cwd=self.cwd)
  File "/content/TaskWeaver/playground/UI/../../taskweaver/ces/environment.py", line 219, in start_session
    self._cmd_session_init(session)
  File "/content/TaskWeaver/playground/UI/../../taskweaver/ces/environment.py", line 572, in _cmd_session_init
    self._execute_control_code_on_kernel(
  File "/content/TaskWeaver/playground/UI/../../taskweaver/ces/environment.py", line 459, in _execute_control_code_on_kernel
    raise Exception("No text returned.")
Exception: No text returned.

```
![Screenshot from 2024-03-28 14-43-24](https://github.com/microsoft/TaskWeaver/assets/156284866/d305a276-e2ea-4468-ae80-a2bb85fc175b)

**Comment by liqul** [comment]
To exclude any environment issues, you can first try running TaskWeaver from a docker container. Refer to https://microsoft.github.io/TaskWeaver/docs/usage/docker for more information.

**Comment by sangeet000007** [comment]
i have tried it locally it had no issue 
the problem is when running in google colab
i have attached the log file 
[task_weaver.log](https://github.com/microsoft/TaskWeaver/files/14799928/task_weaver.log)

**Comment by liqul** [comment]
This error happens when TaskWeaver was trying to bring up a code executor which is a Jupyter process. I'm not sure if this is allowed in google colab environment.
