### ISSUE TITLE
Error while running TaskWeaver

### ISSUE THREAD

**Issue by abrehmaaan** [microsoft/TaskWeaver#282]
I am facing this error:
```=========================================================
 _____         _     _       __
|_   _|_ _ ___| | _ | |     / /__  ____ __   _____  _____
  | |/ _` / __| |/ /| | /| / / _ \/ __ `/ | / / _ \/ ___/
  | | (_| \__ \   < | |/ |/ /  __/ /_/ /| |/ /  __/ /
  |_|\__,_|___/_|\_\|__/|__/\___/\__,_/ |___/\___/_/
=========================================================
Traceback (most recent call last):
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\api\client.py", line 213, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\api\daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
                        ^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\utils\decorators.py", line 44, in inner
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\api\client.py", line 236, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 496, in _make_request
    conn.request(
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 400, in request
    self.endheaders()
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1041, in _send_output
    self.send(msg)
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 979, in send
    self.connect()
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\transport\npipeconn.py", line 25, in connect
    sock.connect(self.npipe_path)
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\transport\npipesocket.py", line 25, in wrapped
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\transport\npipesocket.py", line 76, in connect
    raise e
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\transport\npipesocket.py", line 54, in connect
    handle = win32file.CreateFile(
             ^^^^^^^^^^^^^^^^^^^^^
pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\ces\environment.py", line 143, in __init__
    self.docker_client = docker.from_env()
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\client.py", line 94, in from_env
    return cls(
           ^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\api\client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\api\client.py", line 220, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\__main__.py", line 9, in <module>
    main()
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\__main__.py", line 5, in main
    __main__.main()
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\cli\__main__.py", line 5, in main
    taskweaver()
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\cli\cli.py", line 42, in taskweaver
    ctx.invoke(chat)
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\cli\util.py", line 15, in new_func
    return ctx.invoke(f, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\cli\chat.py", line 19, in chat
    chat_taskweaver(ctx_obj.workspace)
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\chat\console\chat.py", line 520, in chat_taskweaver
    TaskWeaverChatApp(app_dir=app_dir).run()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\chat\console\chat.py", line 409, in __init__
    self.session = self.app.get_session()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\app\app.py", line 65, in get_session
    return self.session_manager.get_session(session_id, prev_round_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\app\session_manager.py", line 29, in get_session
    return self._get_session_from_store(session_id, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\app\session_manager.py", line 87, in _get_session_from_store
    new_session = self.injector.create_object(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 1040, in call_with_injection
    return callable(*full_args, **dependencies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\session\session.py", line 102, in __init__
    role_instance = self.session_injector.create_object(role_entry.module, {"role_entry": role_entry})
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 1031, in call_with_injection
    dependencies = self.args_to_inject(
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 1079, in args_to_inject
    instance: Any = self.get(interface)
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 975, in get
    result = provider_instance.get(self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 1031, in call_with_injection
    dependencies = self.args_to_inject(
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 1079, in args_to_inject
    instance: Any = self.get(interface)
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 975, in get
    result = provider_instance.get(self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 302, in get
    return injector.call_with_injection(self._callable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 1040, in call_with_injection
    return callable(*full_args, **dependencies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\module\execution_service.py", line 39, in provide_executor_manager
    self.manager = code_execution_service_factory(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\ces\__init__.py", line 12, in code_execution_service_factory
    return SubProcessManager(
           ^^^^^^^^^^^^^^^^^^
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\ces\manager\sub_proc.py", line 74, in __init__
    self.env = Environment(
               ^^^^^^^^^^^^
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\ces\environment.py", line 145, in __init__
    raise docker.errors.DockerException(f"Failed to connect to Docker daemon: {e}. ")
docker.errors.DockerException: Failed to connect to Docker daemon: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.').
PS D:\Ahsan Bhai\TaskWeaver> python test.py
Traceback (most recent call last):
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\api\client.py", line 213, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\api\daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
                        ^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\utils\decorators.py", line 44, in inner
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\api\client.py", line 236, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 496, in _make_request
    conn.request(
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 400, in request
    self.endheaders()
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1041, in _send_output
    self.send(msg)
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 979, in send
    self.connect()
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\transport\npipeconn.py", line 25, in connect
    sock.connect(self.npipe_path)
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\transport\npipesocket.py", line 25, in wrapped
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\transport\npipesocket.py", line 76, in connect
    raise e
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\transport\npipesocket.py", line 54, in connect
    handle = win32file.CreateFile(
             ^^^^^^^^^^^^^^^^^^^^^
pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\ces\environment.py", line 143, in __init__
    self.docker_client = docker.from_env()
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\client.py", line 94, in from_env
    return cls(
           ^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\api\client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\docker\api\client.py", line 220, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Ahsan Bhai\TaskWeaver\test.py", line 6, in <module>
    session = app.get_session()
              ^^^^^^^^^^^^^^^^^
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\app\app.py", line 65, in get_session
    return self.session_manager.get_session(session_id, prev_round_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\app\session_manager.py", line 29, in get_session
    return self._get_session_from_store(session_id, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\app\session_manager.py", line 87, in _get_session_from_store
    new_session = self.injector.create_object(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 1040, in call_with_injection
    return callable(*full_args, **dependencies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\session\session.py", line 102, in __init__
    role_instance = self.session_injector.create_object(role_entry.module, {"role_entry": role_entry})
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 1031, in call_with_injection
    dependencies = self.args_to_inject(
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 1079, in args_to_inject
    instance: Any = self.get(interface)
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 975, in get
    result = provider_instance.get(self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 1031, in call_with_injection
    dependencies = self.args_to_inject(
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 1079, in args_to_inject
    instance: Any = self.get(interface)
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 975, in get
    result = provider_instance.get(self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 302, in get
    return injector.call_with_injection(self._callable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abdul\AppData\Local\Programs\Python\Python311\Lib\site-packages\injector\__init__.py", line 1040, in call_with_injection
    return callable(*full_args, **dependencies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\module\execution_service.py", line 39, in provide_executor_manager
    self.manager = code_execution_service_factory(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\ces\__init__.py", line 12, in code_execution_service_factory
    return SubProcessManager(
           ^^^^^^^^^^^^^^^^^^
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\ces\manager\sub_proc.py", line 74, in __init__
    self.env = Environment(
               ^^^^^^^^^^^^
  File "D:\Ahsan Bhai\TaskWeaver\taskweaver\ces\environment.py", line 145, in __init__
    raise docker.errors.DockerException(f"Failed to connect to Docker daemon: {e}. ")
docker.errors.DockerException: Failed to connect to Docker daemon: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.').```

**Comment by liqul** [comment]
Did you have docker installed properly? Please read this [doc](https://microsoft.github.io/TaskWeaver/docs/code_execution) to understand the execution mode. We also support the `local` mode for experimental purpose.

**Comment by liqul** [comment]
close inactive issues
