### ISSUE TITLE
No current event in loop error how to solve

### ISSUE THREAD

**Issue by arhaang13** [microsoft/TaskWeaver#381]
Cannot process your request due to Exception: There is no current event loop in thread 'AnyIO worker thread'.
Traceback (most recent call last):
File "C:\Users\arhaan\anaconda3\envs\taskweaver\lib\site-packages\langchain_community\document_loaders\async_html.py", line 219, in lazy_load
asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\arhaan\Downloads\TaskWeaver-a\TaskWeaver\playground\UI../..\taskweaver\session\session.py", line 202, in _send_text_message
post = _send_message(post.send_to, post)
File "C:\Users\arhaan\Downloads\TaskWeaver-a\TaskWeaver\playground\UI../..\taskweaver\module\tracing.py", line 174, in wrapper
return func(*args, **kwargs)
File "C:\Users\arhaan\Downloads\TaskWeaver-a\TaskWeaver\playground\UI../..\taskweaver\session\session.py", line 182, in _send_message
reply_post = self.worker_instances[recipient].reply(
File "C:\Users\arhaan\Downloads\TaskWeaver-a\TaskWeaver\playground\UI../..\taskweaver\ext_role\web_search\web_search.py", line 199, in reply
browse_page(
File "C:\Users\arhaan\Downloads\TaskWeaver-a\TaskWeaver\playground\UI../..\taskweaver\ext_role\web_search\web_search.py", line 83, in browse_page
docs = loader.load()
File "C:\Users\arhaan\anaconda3\envs\taskweaver\lib\site-packages\langchain_core\document_loaders\base.py", line 30, in load
return list(self.lazy_load())
File "C:\Users\arhaan\anaconda3\envs\taskweaver\lib\site-packages\langchain_community\document_loaders\async_html.py", line 229, in lazy_load
results = asyncio.run(self.fetch_all(self.web_paths))
File "C:\Users\arhaan\anaconda3\envs\taskweaver\lib\site-packages\nest_asyncio.py", line 26, in run
loop = asyncio.get_event_loop()
File "C:\Users\arhaan\anaconda3\envs\taskweaver\lib\site-packages\nest_asyncio.py", line 40, in _get_event_loop
loop = events.get_event_loop_policy().get_event_loop()
File "C:\Users\arhaan\anaconda3\envs\taskweaver\lib\asyncio\events.py", line 656, in get_event_loop
raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'AnyIO worker thread'.

**Comment by liqul** [comment]
Please share more context when this error happened.
