### ISSUE TITLE
Error on creating a new role

### ISSUE THREAD

**Issue by arhaang13** [microsoft/TaskWeaver#382]
2024-07-12 17:38:54 - CodeInterpreter initialized successfully.
2024-07-12 17:38:54 - Unknown role text_reply
Traceback (most recent call last):
  File "/Users/arhaan/anaconda3/envs/taskweaver/lib/python3.11/site-packages/chainlit/utils.py", line 44, in wrapper
    return await user_function(**params_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arhaan/TaskWeaver/playground/UI/app.py", line 383, in start
    app_session_dict[user_session_id] = app.get_session()
                                        ^^^^^^^^^^^^^^^^^
  File "/Users/arhaan/TaskWeaver/playground/UI/../../taskweaver/app/app.py", line 65, in get_session
    return self.session_manager.get_session(session_id, prev_round_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arhaan/TaskWeaver/playground/UI/../../taskweaver/app/session_manager.py", line 29, in get_session
    return self._get_session_from_store(session_id, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arhaan/TaskWeaver/playground/UI/../../taskweaver/app/session_manager.py", line 87, in _get_session_from_store
    new_session = self.injector.create_object(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arhaan/anaconda3/envs/taskweaver/lib/python3.11/site-packages/injector/__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/Users/arhaan/anaconda3/envs/taskweaver/lib/python3.11/site-packages/injector/__init__.py", line 1040, in call_with_injection
    return callable(*full_args, **dependencies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arhaan/TaskWeaver/playground/UI/../../taskweaver/session/session.py", line 101, in __init__
    raise ValueError(f"Unknown role {role_name}")
ValueError: Unknown role text_reply

I get this error unknown role when i have created the role as mentioned under the instructions. Kindly help!

**Comment by dasuni1999** [comment]
@arhaang13, will you be able to let me know how you fixed this issue..?
I keep getting the same error.
