### ISSUE TITLE
Error when trying to run taskweaver from command line

### ISSUE THREAD

**Issue by svidhani** [microsoft/TaskWeaver#51]
Error while trying to run this command -> python3 -m taskweaver -p ./project

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/TaskWeaver/taskweaver/__main__.py", line 1, in <module>
    from .cli import __main__
  File "/TaskWeaver/taskweaver/cli/__main__.py", line 1, in <module>
    from .cli import taskweaver
  File "/TaskWeaver/taskweaver/cli/cli.py", line 3, in <module>
    from ..app import TaskWeaverApp
  File "/TaskWeaver/taskweaver/app/__init__.py", line 1, in <module>
    from .app import TaskWeaverApp
  File "/TaskWeaver/taskweaver/app/app.py", line 9, in <module>
    from taskweaver.module.execution_service import ExecutionServiceModule
  File "/TaskWeaver/taskweaver/module/execution_service.py", line 6, in <module>
    from taskweaver.ces import code_execution_service_factory
  File "/TaskWeaver/taskweaver/ces/__init__.py", line 2, in <module>
    from taskweaver.ces.manager.sub_proc import SubProcessManager
  File "/TaskWeaver/taskweaver/ces/manager/sub_proc.py", line 7, in <module>
    from taskweaver.ces.environment import Environment
  File "/TaskWeaver/taskweaver/ces/environment.py", line 90, in <module>
    class TaskWeaverMultiKernelManager(MultiKernelManager):
  File "/TaskWeaver/taskweaver/ces/environment.py", line 93, in TaskWeaverMultiKernelManager
    kernel_name: str | None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by liqul** [comment]
@svidhani Hi, taskweaver requires at least python 3.10 and you need to upgrade your env.
