### ISSUE TITLE
Unable to communicate with the OpenAI server - due to certificate verification error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)

### ISSUE THREAD

**Issue by risjain** [microsoft/TaskWeaver#52]
**Describe the bug**
Error: Cannot process your request due to Exception: OpenAI API request failed to connect: Connection error.
Traceback (most recent call last):
  File "/root/miniconda3/envs/taskweaver/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/root/miniconda3/envs/taskweaver/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 168, in start_tls
    raise exc
  File "/root/miniconda3/envs/taskweaver/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 163, in start_tls
    sock = ssl_context.wrap_socket(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/taskweaver/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/taskweaver/lib/python3.11/ssl.py", line 1108, in _create
    self.do_handshake()
  File "/root/miniconda3/envs/taskweaver/lib/python3.11/ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/root/miniconda3/envs/taskweaver/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/root/miniconda3/envs/taskweaver/lib/python3.11/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/taskweaver/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/root/miniconda3/envs/taskweaver/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/taskweaver/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/root/miniconda3/envs/taskweaver/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/taskweaver/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 156, in _connect
    stream = stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/taskweaver/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 152, in start_tls
    with map_exceptions(exc_map):
  File "/root/miniconda3/envs/taskweaver/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/miniconda3/envs/taskweaver/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)

**To Reproduce**
1. Start taskweaver as per the instructions on the Github repo
2. Type the user query "Anything"
3. See error

**Expected behavior**
See Taskweaver iterate through the iterations to fulfill the request in the user prompt.

**Environment Information (please complete the following information):**
 - OS: WSL (W11)
 - Python Version 3.11
 - LLM that you're using: [e.g., GPT-4]

**Comment by ShilinHe** [comment]
Hi, we never encountered this error before, could you provide more context? e.g., which LLMs are you using? are you using tools like ollama or litellm?

**Comment by ShilinHe** [comment]
close as no more activity
